<a href="https://colab.research.google.com/github/anjukc/DataScienceLab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
my_list=([1,2,3,4,5])
print(my_list)

[1, 2, 3, 4, 5]


In [6]:
np.arange(1,1)
arr=([1,2,3],[2,3,4],[5,6,7])
np.array(arr)


array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [7]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a=a.astype(int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.random.rand(5)

array([0.44611739, 0.28217306, 0.45665619, 0.52555376, 0.63906404])

In [18]:
np.random.randn(4)

array([0.20703829, 0.33428134, 1.48623005, 1.01076782])

In [19]:
np.random.randint(1,50)

47

In [20]:
array=[2,3,4,5,6,7,8,9]

In [21]:
array

[2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
arr=np.random.randint(1,100,10)
print(arr)
arr.shape


[28 49 88 14  3 78 85 31 81 25]


(10,)

In [25]:
arr.reshape(5,2)

array([[28, 49],
       [88, 14],
       [ 3, 78],
       [85, 31],
       [81, 25]])

In [26]:
arr.max()

88

In [27]:
arr.min()

3

In [28]:
arr.argmax()

2

In [29]:
arr.argmin()

4

In [30]:
arr2=np.arange(0,10)

In [31]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[0:5]

array([28, 49, 88, 14,  3])

In [33]:
arr2[:4]

array([0, 1, 2, 3])

In [34]:
arr2[4:]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr3=np.array([[1,2,3],[4,5,6],[6,7,8]])